spring:
  flyway:
    enabled: true
  application:
    name: "dam"
  datasource:
    url: "jdbc:postgresql://database:5432/data_access"
    username: "postgres"
    password: "secret"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true
  cloud:
    config:
      enabled: false
    compatibility-verifier:
      enabled: false

eureka:
  client:
    enabled: false

server:
  port: 9081

app:
  name: "Access Data Manager Service"
  api:
    title: "Broker - Access Data Manager APIs"
    version: "v1"
    description: "This API expose the model used to place order and trades"
    base-package: "org.broker.dataaccess.controller"
    contact-name: "support"
    contact-email: "support@broker.com"
    swagger:
      enable: true