spring:
  flyway:
    enabled: true
  application:
    name: "adms"
  datasource:
    url: "jdbc:postgresql://localhost:5432/data_access"
    username: "postgres"
    password: "secret"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true

server:
  port: 9081

logging:
  level:
    org:
      springframework: INFO

app:
  name: "Access Data Manager Service"
  api:
    title: "Broker - Access Data Manager APIs"
    version: "v1"
    description: "This API expose the model used to place order and trades"
    base-package: "org.broker.dataaccess.controller"
    contact-name: "support"
    contact-email: "support@broker.com"
    swagger:
      enable: true

